QUOTES_DATABASE = [
    {"content": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "tags": ["work", "passion", "success"], "_id": "1"},
    {"content": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "author": "Winston Churchill", "tags": ["success", "courage", "perseverance"], "_id": "2"},
    {"content": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt", "tags": ["belief", "motivation", "confidence"], "_id": "3"},
    {"content": "Everything you've ever wanted is on the other side of fear.", "author": "George Addair", "tags": ["fear", "motivation", "courage"], "_id": "4"},
    {"content": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "tags": ["dreams", "future", "belief"], "_id": "5"},
    {"content": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "tags": ["time", "perseverance", "motivation"], "_id": "6"},
    {"content": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney", "tags": ["action", "motivation", "success"], "_id": "7"},
    {"content": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "tags": ["perseverance", "success", "patience"], "_id": "8"},
    {"content": "The harder you work for something, the greater you'll feel when you achieve it.", "author": "Unknown", "tags": ["hard work", "success", "achievement"], "_id": "9"},
    {"content": "Opportunities don't happen, you create them.", "author": "Chris Grosser", "tags": ["opportunity", "action", "success"], "_id": "10"},
    {"content": "Do what you can with all you have, wherever you are.", "author": "Theodore Roosevelt", "tags": ["action", "motivation", "success"], "_id": "11"},
    {"content": "Everything you can imagine is real.", "author": "Pablo Picasso", "tags": ["imagination", "creativity", "success"], "_id": "12"},
    {"content": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "tags": ["dreams", "goals", "motivation"], "_id": "13"},
    {"content": "In the middle of every difficulty lies opportunity.", "author": "Albert Einstein", "tags": ["opportunity", "perseverance", "growth"], "_id": "14"},
    {"content": "It always seems impossible until it's done.", "author": "Nelson Mandela", "tags": ["success", "perseverance", "motivation"], "_id": "15"},
    {"content": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "tags": ["success", "impact", "growth"], "_id": "16"},
    {"content": "You don't have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "tags": ["action", "success", "motivation"], "_id": "17"},
    {"content": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "tags": ["belief", "future", "doubt"], "_id": "18"},
    {"content": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman", "tags": ["positivity", "perseverance", "motivation"], "_id": "19"},
    {"content": "The best way to predict the future is to create it.", "author": "Abraham Lincoln", "tags": ["future", "action", "success"], "_id": "20"},
    {"content": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson", "tags": ["inner strength", "perspective", "motivation"], "_id": "21"},
    {"content": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "tags": ["action", "risk", "success"], "_id": "22"},
    {"content": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon", "tags": ["work", "success", "effort"], "_id": "23"},
    {"content": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "tags": ["hardships", "growth", "destiny"], "_id": "24"},
    {"content": "Don’t wait. The time will never be just right.", "author": "Napoleon Hill", "tags": ["action", "timing", "motivation"], "_id": "25"},
    {"content": "You have to be odd to be number one.", "author": "Dr. Seuss", "tags": ["creativity", "success", "uniqueness"], "_id": "26"},
    {"content": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi", "tags": ["resilience", "perseverance", "motivation"], "_id": "27"},
    {"content": "To be the best, you must be able to handle the worst.", "author": "Wilson Kanadi", "tags": ["resilience", "strength", "success"], "_id": "28"},
    {"content": "Your limitation—it’s only your imagination.", "author": "Unknown", "tags": ["imagination", "limitation", "success"], "_id": "29"},
    {"content": "Dream it. Wish it. Do it.", "author": "Unknown", "tags": ["dreams", "action", "success"], "_id": "30"},
    {"content": "Success doesn’t just find you. You have to go out and get it.", "author": "Unknown", "tags": ["success", "action", "effort"], "_id": "31"},
    {"content": "The harder the battle, the sweeter the victory.", "author": "Les Brown", "tags": ["success", "hard work", "victory"], "_id": "32"},
    {"content": "If you can dream it, you can do it.", "author": "Walt Disney", "tags": ["dreams", "action", "success"], "_id": "33"},
    {"content": "Don’t stop when you’re tired. Stop when you’re done.", "author": "Unknown", "tags": ["perseverance", "success", "effort"], "_id": "34"},
    {"content": "Wake up with determination. Go to bed with satisfaction.", "author": "Unknown", "tags": ["determination", "effort", "satisfaction"], "_id": "35"},
    {"content": "Little things make big days.", "author": "Unknown", "tags": ["success", "effort", "motivation"], "_id": "36"},
    {"content": "It always seems impossible until it's done.", "author": "Nelson Mandela", "tags": ["success", "perseverance", "motivation"], "_id": "37"},
    {"content": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "tags": ["time", "perseverance", "motivation"], "_id": "38"},
    {"content": "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "author": "Unknown", "tags": ["strength", "growth", "resilience"], "_id": "39"},
    {"content": "The struggle you’re in today is developing the strength you need for tomorrow.", "author": "Unknown", "tags": ["strength", "growth", "resilience"], "_id": "40"},
    {"content": "The key to success is to focus on goals, not obstacles.", "author": "Unknown", "tags": ["success", "focus", "goals"], "_id": "41"},
    {"content": "Push yourself, because no one else is going to do it for you.", "author": "Unknown", "tags": ["motivation", "self-discipline", "success"], "_id": "42"},
    {"content": "Great things never come from comfort zones.", "author": "Unknown", "tags": ["comfort zone", "growth", "success"], "_id": "43"},
    {"content": "Dream it. Believe it. Build it.", "author": "Unknown", "tags": ["dreams", "belief", "action"], "_id": "44"},
    {"content": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "tags": ["success", "effort", "perseverance"], "_id": "45"},
    {"content": "Your future is created by what you do today, not tomorrow.", "author": "Robert Kiyosaki", "tags": ["future", "action", "success"], "_id": "46"},
    {"content": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson", "tags": ["work", "luck", "success"], "_id": "47"},
    {"content": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "tags": ["action", "success", "motivation"], "_id": "48"},
    {"content": "Don’t count the days, make the days count.", "author": "Muhammad Ali", "tags": ["time", "success", "effort"], "_id": "49"},
    {"content": "What we think, we become.", "author": "Buddha", "tags": ["thoughts", "mindset", "success"], "_id": "50"},
    {"content": "Success is the best revenge.", "author": "Kanye West", "tags": ["success", "revenge", "motivation"], "_id": "51"},
    {"content": "Your limitation—it’s only your imagination.", "author": "Unknown", "tags": ["imagination", "success", "motivation"], "_id": "52"},
    {"content": "Act as if what you do makes a difference. It does.", "author": "William James", "tags": ["action", "impact", "success"], "_id": "53"},
    {"content": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer", "tags": ["success", "happiness", "life"], "_id": "54"},
    {"content": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau", "tags": ["success", "action", "effort"], "_id": "55"},
    {"content": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller", "tags": ["success", "growth", "courage"], "_id": "56"},
    {"content": "I am not a product of my circumstances. I am a product of my decisions.", "author": "Stephen R. Covey", "tags": ["decisions", "success", "growth"], "_id": "57"},
    {"content": "Success is not just about making money. It’s about making a difference.", "author": "Unknown", "tags": ["success", "impact", "difference"], "_id": "58"},
    {"content": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill", "tags": ["success", "failure", "perseverance"], "_id": "59"},
    {"content": "Success is not measured by what you accomplish, but by the obstacles you overcome.", "author": "Unknown", "tags": ["success", "obstacles", "perseverance"], "_id": "60"},
    {"content": "The key to success is to start before you are ready.", "author": "Marie Forleo", "tags": ["success", "action", "motivation"], "_id": "61"},
    {"content": "Success is the result of preparation, hard work, and learning from failure.", "author": "Colin Powell", "tags": ["success", "preparation", "failure"], "_id": "62"},
    {"content": "A dream doesn't become reality through magic; it takes sweat, determination and hard work.", "author": "Colin Powell", "tags": ["dreams", "hard work", "success"], "_id": "63"},
    {"content": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis", "tags": ["success", "failure", "journey"], "_id": "64"},
    {"content": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "tags": ["success", "impact", "growth"], "_id": "65"},
    {"content": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "tags": ["time", "success", "motivation"], "_id": "66"},
    {"content": "Don’t let yesterday take up too much of today.", "author": "Will Rogers", "tags": ["time", "focus", "success"], "_id": "67"},
    {"content": "Success is liking yourself, liking what you do, and liking how you do it.", "author": "Maya Angelou", "tags": ["success", "happiness", "self-love"], "_id": "68"},
    {"content": "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", "author": "Booker T. Washington", "tags": ["success", "obstacles", "perseverance"], "_id": "69"},
    {"content": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "tags": ["success", "perseverance", "motivation"], "_id": "70"},
    {"content": "Success doesn’t come from what you do occasionally, it comes from what you do consistently.", "author": "Marie Forleo", "tags": ["success", "consistency", "effort"], "_id": "71"},
    {"content": "Success is a journey, not a destination.", "author": "Ben Sweetland", "tags": ["success", "journey", "life"], "_id": "72"},
    {"content": "Success is the progressive realization of a worthy goal or ideal.", "author": "Earl Nightingale", "tags": ["success", "goal", "life"], "_id": "73"},
    {"content": "Success is about creating value.", "author": "Cameron Herold", "tags": ["success", "value", "entrepreneurship"], "_id": "74"},
    {"content": "A goal is not always meant to be reached, it often serves simply as something to aim at.", "author": "Bruce Lee", "tags": ["goals", "success", "motivation"], "_id": "75"},
    {"content": "Success is to be achieved in small increments, not all at once.", "author": "Unknown", "tags": ["success", "patience", "effort"], "_id": "76"},
    {"content": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein", "tags": ["mistakes", "growth", "success"], "_id": "77"},
    {"content": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "tags": ["believe", "success", "impossible"], "_id": "78"},
    {"content": "Success is not in what you have, but who you are.", "author": "Bo Bennett", "tags": ["success", "self-worth", "life"], "_id": "79"},
    {"content": "The secret of getting ahead is getting started.", "author": "Mark Twain", "tags": ["action", "success", "motivation"], "_id": "80"},
    {"content": "Success is what happens after you have survived all your mistakes.", "author": "Unknown", "tags": ["success", "mistakes", "growth"], "_id": "81"},
    {"content": "Success is about making progress, not achieving perfection.", "author": "Unknown", "tags": ["success", "progress", "growth"], "_id": "82"},
    {"content": "Success is the result of learning from the failures and striving again.", "author": "Unknown", "tags": ["success", "failure", "growth"], "_id": "83"},
    {"content": "Success is not the absence of failure; it's the persistence through failure.", "author": "Aisha Tyler", "tags": ["success", "failure", "perseverance"], "_id": "84"},
    {"content": "Success is not for the chosen few; it is for the few who choose to work for it.", "author": "Unknown", "tags": ["success", "work", "effort"], "_id": "85"},
    {"content": "Success is the ability to go from one failure to another with no loss of enthusiasm.", "author": "Winston Churchill", "tags": ["success", "failure", "enthusiasm"], "_id": "86"},
    {"content": "Success is a state of mind. If you want success, start thinking of yourself as a success.", "author": "Joyce Brothers", "tags": ["mindset", "success", "growth"], "_id": "87"},
    {"content": "Success is when the time you spend enjoying life is greater than the time you spend working.", "author": "Unknown", "tags": ["success", "work-life balance", "enjoyment"], "_id": "88"},
]